name: "Fab's Travels"
favicon: null
layout_spectrum: 0.038982817670330405
typography_spectrum: 0.26786665711551905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4847741562407464
  lightness: 0.3084778788033873
  saturation: 0.838170015020296
  rhythmicContrast: 0.8802257939241827
purpose: []
